name = "Apo"
license = "MIT"
licenselink = "https://github.com/jacopodonati/hugo-theme-apo/blob/master/LICENSE"
description = ""
homepage = "https://www.jacopodonati.it/"
tags = ["light", "dark", "minimal"]
features = []
min_version = "0.93.0"

[author]
  name = "Jacopo Donati"
  homepage = "https://www.jacopodonati.it/"